version: '3.4'

services:
  ecommerce-postgresql:
     image: postgres:latest
     container_name: ecommerce-postgresql
     # volumes:
     #     - ~/volumes/jhipster/schoolservice/postgresql/:/var/lib/postgresql/data/
     environment:
        - POSTGRES_DB=angular32
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=remote
     ports:
        - 5410:5432

  ecommerce-backend:
     image: dimmxx/fullstack-springboot-angular-ecommerce-postgres:latest
     container_name: ecommerce-backend
     ports:
        - 8010:8010
     environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce-postgresql:5410/angular32
        - SPRING_DATASOURCE_USERNAME=user
        - SPRING_DATASOURCE_USERNAME=remote