version: '3.8'

services:
  ecommerce-postgresql:
     image: postgres:latest
     container_name: ecommerce-postgresql
     # volumes:
     #     - ~/volumes/jhipster/schoolservice/postgresql/:/var/lib/postgresql/data/
     environment:
        - POSTGRES_DB=fullstackecommerce
        - POSTGRES_USER=ecommerce
        - POSTGRES_PASSWORD=remote
     ports:
        - 5455:5432

  ecommerce:
     image: dimmxx/fullstack-springboot-angular-ecommerce-postgres:latest
     container_name: ecommerce-backend
     ports:
        - 8090:8090
     environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce-postgresql:5455/fullstackecommerce

